[versions]
android-activity = "1.9.0"
android-appcompat = "1.6.1"
android-constraintlayout = "2.1.4"
android-core = "1.13.1"
android-fragment = "1.7.1"

material = "1.12.0"
picasso = "2.71828"

android-application = "8.4.0"
android-library = "8.4.0"
kotlin-android = "1.9.23"
detekt = "1.21.0"

[libraries]
androidx-activity = { group = "androidx.activity", name = "activity-ktx", version.ref = "android-activity" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "android-appcompat" }
androidx-core = { group = "androidx.core", name = "core-ktx", version.ref = "android-core" }
androidx-material = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "android-constraintlayout" }
androidx-fragment = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "android-fragment" }

google-material = { group = "com.google.android.material", name = "material", version.ref = "material" }
picasso = { group = "com.squareup.picasso", name = "picasso", version.ref = "picasso" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-application" }
android-library = { id = "com.android.library", version.ref = "android-library" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-android" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }


